# Generated by Django 3.1.3 on 2020-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
