# Generated by Django 3.1.3 on 2020-11-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20201125_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action',
            new_name='typeaction',
        ),
    ]
